
/*1. Escribe una función que escriba “Hola” 3 veces.*/

/*funcionHola("hola1", "hola2", "hola3")/*error, Esto es un dato, aqui se ponen argumentos, definicionesno, no datos en la funcion.
console.log("")*/

/*saludoJuancarlos("Hola","Hola","Hola") //no es lo quepide el ejercicio//
function saludoJuancarlos(Arg1,Arg2,Arg3,){

    console.log(Arg1)
    console.log(Arg2)
    console.log(Arg3)
}*/

//con un for//
function saludo(){
 /*   console.log("Hola")
    console.log("Hola")
    console.log("Hola")
*/
for (let i = 0; i < 3; i++) {
    console.log("Hola")
}
}
